#!/bin/bash
# Auto-fill reproducibility/environment_manifest_template.yaml fields from a live host.
IMG=${1:-vllm/vllm-openai:latest}
echo "schema_version: 1"
echo "captured_at_utc: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "host:"
echo "  hostname_hash: $(hostname | sha256sum | cut -c1-16)"
echo "  cpu_model: \"$(lscpu | sed -n 's/^Model name: *//p' | head -1)\""
echo "  numa_nodes: $(lscpu | sed -n 's/^NUMA node(s): *//p')"
echo "  ram_gib: $(free -g | awk '/^Mem:/{print $2}')"
echo "  local_nvme_gib: $(df -BG --output=size / | tail -1 | tr -dc 0-9)"
echo "gpu:"
echo "  product_name: \"$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)\""
echo "  count: $(nvidia-smi --list-gpus | wc -l)"
echo "  memory_mib_per_gpu: $(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -1)"
echo "  compute_capability: $(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | head -1)"
echo "  power_limit_w: $(nvidia-smi --query-gpu=power.limit --format=csv,noheader,nounits | head -1)"
echo "  ecc_mode: $(nvidia-smi --query-gpu=ecc.mode.current --format=csv,noheader | head -1)"
echo "  uuid_hashes: [$(nvidia-smi --query-gpu=uuid --format=csv,noheader | while read u; do printf '"%s",' $(echo $u|sha256sum|cut -c1-12); done | sed 's/,$//')]"
echo "fabric:"
echo "  nvlink_status: \"$(nvidia-smi nvlink -s 2>&1 | head -1 | tr -d '\n' | cut -c1-60)\""
echo "  topo_matrix: |"
nvidia-smi topo -m 2>/dev/null | sed 's/^/    /' | head -6
echo "software:"
echo "  os_release: \"$(. /etc/os-release; echo $PRETTY_NAME)\""
echo "  kernel: $(uname -r)"
echo "  nvidia_driver: $(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1)"
echo "  cuda_driver_api: $(nvidia-smi | sed -n 's/.*CUDA Version: *\([0-9.]*\).*/\1/p' | head -1)"
echo "  container_image: $IMG"
echo "  container_digest: $(docker inspect $IMG --format '{{index .RepoDigests 0}}' 2>/dev/null)"
echo "  backend_version: $(docker run --rm --entrypoint python3 $IMG -c 'import vllm;print(vllm.__version__)' 2>/dev/null | tail -1)"
echo "  torch_version: $(docker run --rm --entrypoint python3 $IMG -c 'import torch;print(torch.__version__)' 2>/dev/null | tail -1)"
echo "thermal_baseline:"
echo "  idle_gpu_temp_c: [$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader | paste -sd,)]"
echo "  idle_power_w: [$(nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits | paste -sd,)]"
echo "  throttle_reasons: \"$(nvidia-smi --query-gpu=clocks_throttle_reasons.active --format=csv,noheader | head -1)\""
